version: '3'

services:
  lumen:
    image: ponto-api/lumen
    container_name: PontoApi
    ports:
      - "8000:8000"
    volumes:
        - .:/var/www

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ponto
